---
title: "CodeBook"
author: "Michael Addonisio"
date: "August 23, 2015"
output: html_document
---

This project contains one R script, run_analysis.R,  that preforms the following functions. 

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names. 
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

##Variables 
- The data used is comprised of the following files: x_train, y_train, x_test, y_test, subject_train and subject_test
- These files will be merged into a final complete dataset, defined as dataset
- this dataset will be maniplulated to find the mean average per variable,subject and activitiy. This dataset will be outputed and called tidydata.txt



